// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJF_oFqxB12Z9nrVFiWgvqyeddighg91M',
    appId: '1:507312885678:web:f212715032d7fe78aa423f',
    messagingSenderId: '507312885678',
    projectId: 'juno-driver-e4b81',
    authDomain: 'juno-driver-e4b81.firebaseapp.com',
    storageBucket: 'juno-driver-e4b81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9nQbQqT0VBtSPjsR61YmC3Fcfw-mMDc',
    appId: '1:507312885678:android:8503c19e5b30e4eeaa423f',
    messagingSenderId: '507312885678',
    projectId: 'juno-driver-e4b81',
    storageBucket: 'juno-driver-e4b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3cwMH6rAXTGuSXOChjDQxMBPBqYInoM',
    appId: '1:507312885678:ios:234b15ad9da99078aa423f',
    messagingSenderId: '507312885678',
    projectId: 'juno-driver-e4b81',
    storageBucket: 'juno-driver-e4b81.appspot.com',
    iosClientId: '507312885678-q01mfq37dlk5m49ro24og4l720foe5qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl3cwMH6rAXTGuSXOChjDQxMBPBqYInoM',
    appId: '1:507312885678:ios:234b15ad9da99078aa423f',
    messagingSenderId: '507312885678',
    projectId: 'juno-driver-e4b81',
    storageBucket: 'juno-driver-e4b81.appspot.com',
    iosClientId: '507312885678-q01mfq37dlk5m49ro24og4l720foe5qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );
}
